export const REQUEST_ACTION_TYPE = {
  GET_REQUEST_LIST: 'GET_REQUEST_LIST',
  POST_REQUEST: 'POST_REQUEST',
  UPDATE_REQUEST: 'UPDATE_REQUEST'
}

export const COMMON_ACTION_TYPES = {
  REQUEST: '_REQUEST',
  SUCCESS: '_SUCCESS',
  ERROR: '_ERROR',
  CLEAR: '_CLEAR',
  SET_ALERT_REQ: '_SET_ALERT_REQ',
  SET_ALERT: '_SET_ALERT',
  CLEAR_ALERT: '_CLEAR_ALERT'
}

export const APP_ACTION_STATUS = {
  SUCCESS: 'success',
  ERROR: 'error',
  LOADING: 'loading',
  INITIAL: 'intial'
}